export type LanguagePreference = "system" | "zh" | "en";
export type ResolvedLanguage = "zh" | "en";
export type ThemePreference = "system" | "light" | "dark";
export type ResolvedTheme = "light" | "dark";

export function resolveLanguage(preference: LanguagePreference): ResolvedLanguage {
  if (preference === "zh" || preference === "en") {
    return preference;
  }
  if (typeof navigator !== "undefined" && navigator.language.toLowerCase().startsWith("zh")) {
    return "zh";
  }
  return "en";
}

export function resolveTheme(preference: ThemePreference): ResolvedTheme {
  if (preference === "light" || preference === "dark") {
    return preference;
  }
  if (typeof window !== "undefined" && window.matchMedia("(prefers-color-scheme: dark)").matches) {
    return "dark";
  }
  return "light";
}

export const COPY = {
  zh: {
    appTitle: "iDeer",
    desktopTitle: "iDeer Desktop",
    brandSubtitle: "每日智能简报",
    previewBadge: "预览",
    statusConnecting: "等待连接服务",
    statusConnected: "服务已连接",
    statusWaitingDesktop: "等待启动本地服务",
    statusWaitingWeb: "请先启动 Python 后端",
    statusBackendStarted: "本地服务已启动",
    statusBackendStopped: "已停止托管服务",
    statusConfigSaved: "配置已保存",
    statusConfigSavedLocal: "配置已保存（已保存到本地客户端配置）",
    statusRunDone: (date: string) => `完成于 ${date}`,
    statusRunExited: "任务退出",
    statusSocketError: "WebSocket 连接异常",
    windowControls: {
      minimize: "最小化窗口",
      maximize: "最大化窗口",
      restore: "还原窗口",
      close: "关闭窗口",
    },
    common: {
      unknownError: "发生未知错误",
      itemsCount: (count: number) => `${count} 项`,
    },
    runtime: {
      backendStartingLog: "[iDeer] 正在启动本地服务...",
      backendStartedLog: "[iDeer] 本地服务已启动。",
      backendStartFailedLog: "[iDeer] 启动失败",
      backendHealthCheckFailed: "本地服务进程已尝试启动，但健康检查仍未通过。",
      backendHealthCheckHint: "请确认 Python 解释器路径正确，且该环境已安装 FastAPI、Uvicorn、Pydantic。",
      backendLogLabel: "后端日志：",
      smtpServerRequired: "请先填写 SMTP 服务器。",
      smtpSenderRequired: "请先填写发件邮箱。",
      smtpPasswordRequired: "请先填写 SMTP 密码。",
      smtpReceiverRequired: "请先填写收件邮箱。",
    },
    sidebar: {
      home: "概览",
      library: "资料库",
      status: "当前状态",
    },
    home: {
      title: "欢迎回来",
      description: "在这里运行今日简报、查看历史结果，以及管理你的常用配置。",
      openSettings: "打开用户中心",
      runBlockedBackend: "请先启动本地服务，运行按钮才会可用。",
      runBlockedSources: "请至少选择一个信息源。",
      runBlockedRunning: "当前任务仍在运行中，请等待完成。",
      backend: "后端服务",
      online: "在线",
      offline: "离线",
      startBackend: "启动本地服务",
      startingBackend: "启动中...",
      refresh: "刷新数据",
      refreshing: "刷新中...",
      stopBackend: "停止托管服务",
      model: "模型配置",
      mail: "邮件投递",
      mailReady: "已配置",
      mailPending: "待配置",
      noReceiver: "尚未设置默认接收邮箱",
      sources: "信息源",
      sourcesHint: "选择今天要使用的信息源",
      selectedSources: (count: number) => `已选 ${count} 个信息源`,
      comingSoon: "即将支持",
      comingSoonToast: "更多信息源正在准备中",
      noSourcesActive: "尚未开启信息源。",
      recentRuns: "最近结果",
      noHistory: "还没有历史记录，先运行一轮看看。",
    },
    welcome: {
      title: "欢迎来到 iDeer",
      subtitle: "先完成这几个基础设置，之后就可以直接进入主界面。",
      releaseDate: (date: string) => `发布日期 ${date}`,
      profileTitle: "认识一下你",
      profileHint: "先选头像，再填写名称和收件邮箱。",
      directionTitle: "研究方向",
      directionHint: "先用一段话概述你的科研方向和兴趣，再补充几个英文关键词。",
      modelTitle: "大模型",
      modelHint: "不填写时会尝试使用内置配置，但更建议填写你自己的模型服务。",
      mailTitle: "邮箱",
      mailHint: "收件邮箱必填。发件邮箱不填时会尝试使用默认服务，但稳定性较弱。",
      sourceTitle: "信息源",
      sourceHint: "默认勾选一部分常用来源，你也可以按需要增减。",
      next: "下一步",
      back: "上一步",
      customMode: "自定义模式（推荐）",
      managedMode: "依赖我们的服务",
      customModelHint: "推荐填写你自己的模型配置，并可先做连通性测试。",
      managedModelHint: "将优先依赖我们的默认模型服务，可能不稳定。",
      customMailHint: "推荐填写你自己的 SMTP 发件配置。",
      managedMailHint: "仅保留收件邮箱，发件将尝试使用默认服务。",
      receiverHint: "收件邮箱独立于 SMTP 发件设置。",
      selfProfileHint: "笼统概述一下你的科研方向、兴趣和长期关注主题。",
      directionInputPlaceholder: "输入英文方向，例如 Digital Humanities",
      complete: "完成并进入 iDeer",
      completing: "正在保存...",
      requiredHint: "请先完成当前步骤里的必填内容。",
    },
    workbench: {
      title: "运行面板",
      run: "开始运行",
      running: "运行中...",
      receiver: "接收邮箱",
      deliveryMode: "投递模式",
      sourceEmails: "按来源分别发送",
      combinedReport: "合并汇总发送",
      both: "两者都发",
      quickSettings: "本次设置",
      readyToRun: "准备开始",
      report: "生成跨源报告",
      ideas: "生成研究想法",
      save: "保存历史结果",
      description: "兴趣描述",
      positiveTags: "正向偏好",
      negativeTags: "负向过滤",
      positivePlaceholder: "输入想关注的主题，逗号分隔或回车添加",
      negativePlaceholder: "输入想屏蔽的主题，逗号分隔或回车添加",
      addTag: "添加",
      saveInterest: "保存为默认兴趣",
      savingInterest: "保存中...",
      scholarUrl: "Scholar URL",
      extraX: "本次追加 X 账号",
      researcherProfile: "研究者画像",
      advanced: "高级设置",
      logs: "实时日志",
      outputs: "输出文件",
      runStates: {
        idle: "待运行",
        running: "运行中",
        done: "已完成",
        error: "失败",
      },
      outputEmpty: "完成后会在这里列出本次生成的文件。",
      logEmpty: "运行后这里会显示实时输出。",
      refreshHistory: "刷新历史",
    },
    library: {
      title: "历史运行记录",
      refresh: "刷新",
      refreshing: "刷新中...",
      empty: "暂无历史记录。",
      details: "结果详情",
      emptyDetails: "选择左侧记录查看 Markdown、HTML 和 JSON 输出。",
      noMarkdown: "无 Markdown 文件",
      noHtml: "无 HTML 文件",
      noJson: "无 JSON 文件",
    },
    settings: {
      controlCenter: "控制中心",
      userCenter: "用户中心",
      basic: "基础设置",
      save: "保存设置",
      saving: "保存中...",
      preferences: "偏好",
      language: "语言",
      theme: "显示模式",
      followSystem: "跟随系统",
      chinese: "中文",
      english: "English",
      dark: "深色",
      light: "浅色",
      model: "模型与投递配置",
      content: "内容偏好",
      advanced: "高级设置",
      provider: "接口协议",
      modelName: "模型名称",
      temperature: "温度",
      baseUrl: "接口地址",
      apiKey: "API 密钥",
      smtpServer: "SMTP 服务器",
      smtpPort: "SMTP 端口",
      sender: "发件邮箱",
      receiver: "收件邮箱",
      smtpPassword: "SMTP 密码",
      ghLanguages: "GitHub Languages",
      ghSince: "GitHub Since",
      ghMaxRepos: "GitHub Max Repos",
      hfContentTypes: "HF Content Types",
      hfMaxPapers: "HF Max Papers",
      hfMaxModels: "HF Max Models",
      xRapidApiKey: "X RapidAPI Key",
      xRapidApiHost: "X RapidAPI Host",
      arxivCategories: "arXiv Categories",
      arxivMaxEntries: "arXiv Max Entries",
      arxivMaxPapers: "arXiv Max Papers",
      description: "默认兴趣描述",
      researcherProfile: "研究者画像",
      xAccounts: "X 账号池",
      userName: "名称",
      userReceiver: "收件邮箱",
      userFocus: "研究方向关键词",
      userSelfProfile: "用户自述",
      userSelfProfilePlaceholder: "我正在研究……",
      defaultDeliveryMode: "默认投递模式",
      logLevel: "日志级别",
      logLevelProgress: "仅进度",
      logLevelStandard: "标准",
      logLevelVerbose: "详细",
      visibleSources: "显示的信息源",
      visibleSourcesHint: "勾选后会在概览页显示，默认全部开启。",
      avatar: "头像",
      profile: "用户画像",
      appSettings: "应用设置",
      subscriptionSettings: "订阅服务设置",
      sourceSubscriptions: "信息源订阅",
      modelService: "大模型服务",
      senderSettings: "发件邮箱设置",
      mailHostingSettings: "邮件托管",
      showSourceDetails: "详细设置",
      hideSourceDetails: "收起设置",
      sourceDetailTitle: (name: string) => `${name} 详细设置`,
      sourceDetailHint: "这里只展示当前信息源真正相关的参数，避免把所有抓取配置混在一起。",
      sourceDetailEmpty: "选择一个信息源的“详细设置”后，会在这里显示对应参数。",
      showApiKey: "显示 API Key",
      hideApiKey: "隐藏 API Key",
      showPassword: "显示密码",
      hidePassword: "隐藏密码",
      help: "使用说明",
      subscriptionHelp: "这里用于配置模型服务和订阅抓取所依赖的核心能力。推荐优先选择“自定义模式”，填写你自己的 Provider、Model、Base URL 和 API Key；常见来源通常是 OpenAI、OpenRouter、兼容 OpenAI 协议的中转服务，或你自建的推理网关。若暂时没有可用模型，也可以切换到“依赖我们的服务”，但稳定性、额度和可用性都不保证。",
      sourceSubscriptionHelp: "这里用于管理信息源订阅和抓取策略。主界面只保留信息源开关；每个来源的细项参数请通过“详细设置”分别配置。",
      modelServiceHelp: "这里专门配置大模型服务。当前桌面端只支持 OpenAI 兼容格式，因此 Provider 固定为 openai。自定义模式下请填写你自己的 Model、Base URL 和 API Key；常见来源通常是 OpenAI、OpenRouter、兼容 OpenAI 协议的中转服务，或你自建的推理网关。连通性测试仅在自定义模式下可用，建议保存前做一次快速检查。",
      sourceAdvancedWarningTitle: "高风险配置区",
      sourceAdvancedWarningBody: "除非你明确知道这些抓取参数、账号池或 API 凭证会如何影响结果，否则请谨慎修改。更稳妥的做法是先查看 README 或项目文档，再调整这里的内容。",
      mailHelp: "这里专门配置邮件托管。推荐优先填写你自己的 SMTP 服务器、端口、发件邮箱和密码；Gmail、Outlook、QQ 邮箱、企业邮箱等通常都能在后台找到相应配置。若切换到“依赖我们的服务”，会尝试使用托管发信，但稳定性、隐私与可用性都不如自托管。“发送测试邮件”仅在自定义模式下可用，会按当前配置向收件邮箱发送一封测试邮件，建议保存前先试一次。",
      managedMailHint: "留空时会尝试使用 iDeer 托管发信，但稳定性和隐私都不如自托管邮箱。",
      managedMailTooltip: "如果不填写发件邮箱设置，会尝试使用运营邮箱代发，但这并不稳定。涉及隐私和稳定性时，建议托管自己的邮箱服务。",
      connectionHint: "使用当前 Base URL、API Key 和可选的 Model 做一次 OpenAI 兼容接口探测。会优先请求 /models，必要时回退到一次最小 chat/completions。",
      desktopPythonPath: "Python 解释器路径",
      desktopPythonHint: "仅桌面调试使用。填写后，启动本地服务会优先使用这个解释器，例如你的 conda 环境里的 python.exe。",
      testConnection: "测试连通性",
      testingConnection: "测试中...",
      smtpConnectionHint: "按当前 SMTP 配置向收件邮箱发送一封测试邮件。",
      testSmtp: "发送测试邮件",
      testingSmtp: "发送中...",
      saveProfile: "保存用户信息",
      profileSaved: "用户信息已保存",
    },
    info: {
      title: "关于 iDeer",
      slogan: "把每日值得关注的信息整理成一份清晰简报。",
      disclaimerTitle: "声明",
      disclaimer: "iDeer 仅作为科研辅助与信息整理工具提供，不构成任何学术、法律、投资、医疗或合规建议。软件中接入的第三方模型、搜索源、邮件服务与公开网页内容，可能存在延迟、错误、缺漏、偏见、访问限制或地区性不可用的情况；自动生成的摘要、标签、推荐与结论也可能出现误判，因此不应直接替代你自己的检索、判断与人工复核。使用者需自行确认内容来源、版权边界、平台政策、邮件发送规范、数据安全要求以及所在地区适用的法律法规，并独立承担由配置、抓取、转发、分享或二次使用所带来的责任与风险。",
      authors: "主要贡献者",
      contributorGithubAria: (name: string) => `打开 ${name} 的 GitHub 主页`,
      website: "个人网站",
      githubId: "GitHub ID",
      github: "打开 GitHub 仓库",
      star: "帮我点个star吧 求求你了",
      version: "桌面原型",
      stack: "Tauri + React + Python",
      close: "关闭",
      online: "服务在线",
      offline: "服务离线",
    },
    controls: {
      user: "用户",
      info: "Info",
      theme: "主题",
      language: "语言",
    },
    user: {
      fallbackName: "这倒是提醒我了",
      fallbackFocus: "设置你的研究方向",
      openProfile: "打开用户画像",
    },
    sourceDescriptions: {
      github: "Trending 仓库和工程动态",
      huggingface: "论文与模型动态",
      twitter: "账号时间线和圈层信号",
      arxiv: "新论文抓取与筛选",
    },
    comingSoonSources: {
      wos: "Web of Science",
      cnki: "知网",
      wechat: "微信公众号",
      scholar: "Google Scholar",
    },
    currentModelMissing: "未配置",
  },
  en: {
    appTitle: "iDeer",
    desktopTitle: "iDeer Desktop",
    brandSubtitle: "Daily intelligence briefings",
    previewBadge: "Preview",
    statusConnecting: "Waiting for service connection",
    statusConnected: "Service connected",
    statusWaitingDesktop: "Waiting for local service",
    statusWaitingWeb: "Start the Python backend first",
    statusBackendStarted: "Local service started",
    statusBackendStopped: "Managed service stopped",
    statusConfigSaved: "Settings saved",
    statusConfigSavedLocal: "Settings saved locally to the client",
    statusRunDone: (date: string) => `Completed on ${date}`,
    statusRunExited: "Run exited",
    statusSocketError: "WebSocket connection error",
    windowControls: {
      minimize: "Minimize window",
      maximize: "Maximize window",
      restore: "Restore window",
      close: "Close window",
    },
    common: {
      unknownError: "An unknown error occurred",
      itemsCount: (count: number) => `${count} item${count === 1 ? "" : "s"}`,
    },
    runtime: {
      backendStartingLog: "[iDeer] Starting local service...",
      backendStartedLog: "[iDeer] Local service started.",
      backendStartFailedLog: "[iDeer] Startup failed",
      backendHealthCheckFailed: "The local service was started, but the health check still did not pass.",
      backendHealthCheckHint: "Please verify the Python interpreter path and make sure FastAPI, Uvicorn, and Pydantic are installed in that environment.",
      backendLogLabel: "Backend log:",
      smtpServerRequired: "Please fill in the SMTP server first.",
      smtpSenderRequired: "Please fill in the sender email first.",
      smtpPasswordRequired: "Please fill in the SMTP password first.",
      smtpReceiverRequired: "Please fill in the receiver email first.",
    },
    sidebar: {
      home: "Overview",
      library: "Library",
      status: "Current",
    },
    home: {
      title: "Welcome back",
      description: "Run today's briefing, review past results, and manage your common settings here.",
      openSettings: "Open user hub",
      runBlockedBackend: "Start the local service before running.",
      runBlockedSources: "Choose at least one source to continue.",
      runBlockedRunning: "A run is already in progress. Please wait.",
      backend: "Backend service",
      online: "Online",
      offline: "Offline",
      startBackend: "Start local service",
      startingBackend: "Starting...",
      refresh: "Refresh",
      refreshing: "Refreshing...",
      stopBackend: "Stop managed service",
      model: "Model",
      mail: "Email delivery",
      mailReady: "Configured",
      mailPending: "Not configured",
      noReceiver: "No default receiver yet",
      sources: "Sources",
      sourcesHint: "Choose the sources for this run",
      selectedSources: (count: number) => `${count} source${count === 1 ? "" : "s"} selected`,
      comingSoon: "Coming soon",
      comingSoonToast: "More sources are on the way",
      noSourcesActive: "No source enabled yet.",
      recentRuns: "Recent runs",
      noHistory: "No history yet. Run something to get started.",
    },
    welcome: {
      title: "Welcome to iDeer",
      subtitle: "Finish a few basics first, then we can take you straight into the app.",
      releaseDate: (date: string) => `Released ${date}`,
      profileTitle: "Your profile",
      profileHint: "Pick an avatar, then enter your name and receiver email.",
      directionTitle: "Research directions",
      directionHint: "Start with a broad self-description, then add a few English keywords.",
      modelTitle: "LLM setup",
      modelHint: "If left blank, iDeer will try a built-in default, but your own model setup is recommended.",
      mailTitle: "Mail setup",
      mailHint: "Receiver email is required. If sender is empty, iDeer will try the managed mail service, which may be less stable.",
      sourceTitle: "Sources",
      sourceHint: "A few common sources are enabled by default. You can adjust them here.",
      next: "Next",
      back: "Back",
      customMode: "Custom (Recommended)",
      managedMode: "Use our service",
      customModelHint: "Recommended: use your own model endpoint and test the connection here.",
      managedModelHint: "iDeer will fall back to the managed model service when available. Stability may vary.",
      customMailHint: "Recommended: configure your own SMTP sender.",
      managedMailHint: "Only the receiver address is needed. Sender will rely on the managed service.",
      receiverHint: "Receiver email is independent from SMTP sender settings.",
      selfProfileHint: "Give a broad summary of your research direction, interests, and long-term themes.",
      directionInputPlaceholder: "Add a direction, e.g. Digital Humanities",
      complete: "Finish and enter iDeer",
      completing: "Saving...",
      requiredHint: "Please complete the required fields for this step first.",
    },
    workbench: {
      title: "Run panel",
      run: "Run now",
      running: "Running...",
      receiver: "Receiver email",
      deliveryMode: "Delivery mode",
      sourceEmails: "Source-wise",
      combinedReport: "Combined",
      both: "Send both",
      quickSettings: "Run settings",
      readyToRun: "Ready to run",
      report: "Generate cross-source report",
      ideas: "Generate research ideas",
      save: "Save run history",
      description: "Interest description",
      positiveTags: "Positive",
      negativeTags: "Negative",
      positivePlaceholder: "Add preferred topics with commas or Enter",
      negativePlaceholder: "Add filtered topics with commas or Enter",
      addTag: "Add",
      saveInterest: "Save as default",
      savingInterest: "Saving...",
      scholarUrl: "Scholar URL",
      extraX: "Extra X accounts",
      researcherProfile: "Research profile",
      advanced: "Advanced settings",
      logs: "Live logs",
      outputs: "Output files",
      runStates: {
        idle: "Idle",
        running: "Running",
        done: "Done",
        error: "Error",
      },
      outputEmpty: "Generated files will appear here after the run finishes.",
      logEmpty: "Live output will appear here once the run starts.",
      refreshHistory: "Refresh history",
    },
    library: {
      title: "Run history",
      refresh: "Refresh",
      refreshing: "Refreshing...",
      empty: "No history yet.",
      details: "Result details",
      emptyDetails: "Choose a run on the left to inspect Markdown, HTML and JSON outputs.",
      noMarkdown: "No Markdown files",
      noHtml: "No HTML files",
      noJson: "No JSON files",
    },
    settings: {
      controlCenter: "Control center",
      userCenter: "User hub",
      basic: "Basic settings",
      save: "Save settings",
      saving: "Saving...",
      preferences: "Preferences",
      language: "Language",
      theme: "Theme",
      followSystem: "Follow system",
      chinese: "中文",
      english: "English",
      dark: "Dark",
      light: "Light",
      model: "Model & delivery",
      content: "Content preferences",
      advanced: "Advanced settings",
      provider: "Provider",
      modelName: "Model",
      temperature: "Temperature",
      baseUrl: "Base URL",
      apiKey: "API Key",
      smtpServer: "SMTP Server",
      smtpPort: "SMTP Port",
      sender: "Sender",
      receiver: "Receiver",
      smtpPassword: "SMTP Password",
      ghLanguages: "GitHub Languages",
      ghSince: "GitHub Since",
      ghMaxRepos: "GitHub Max Repos",
      hfContentTypes: "HF Content Types",
      hfMaxPapers: "HF Max Papers",
      hfMaxModels: "HF Max Models",
      xRapidApiKey: "X RapidAPI Key",
      xRapidApiHost: "X RapidAPI Host",
      arxivCategories: "arXiv Categories",
      arxivMaxEntries: "arXiv Max Entries",
      arxivMaxPapers: "arXiv Max Papers",
      description: "Default interest description",
      researcherProfile: "Research profile",
      xAccounts: "X account pool",
      userName: "Name",
      userReceiver: "Receiver email",
      userFocus: "Research keywords",
      userSelfProfile: "Research self-description",
      userSelfProfilePlaceholder: "I am currently working on...",
      defaultDeliveryMode: "Default delivery mode",
      logLevel: "Log level",
      logLevelProgress: "Progress only",
      logLevelStandard: "Standard",
      logLevelVerbose: "Verbose",
      visibleSources: "Visible sources",
      visibleSourcesHint: "Checked sources appear on Home. All are enabled by default.",
      avatar: "Avatar",
      profile: "User profile",
      appSettings: "App settings",
      subscriptionSettings: "Subscription services",
      sourceSubscriptions: "Source subscriptions",
      modelService: "Model service",
      senderSettings: "Sender email settings",
      mailHostingSettings: "Mail hosting",
      showSourceDetails: "Details",
      hideSourceDetails: "Hide details",
      sourceDetailTitle: (name: string) => `${name} details`,
      sourceDetailHint: "Only settings related to the current source are shown here, so fetch options stay easier to reason about.",
      sourceDetailEmpty: "Choose a source's detail view to configure its source-specific options here.",
      showApiKey: "Show API key",
      hideApiKey: "Hide API key",
      showPassword: "Show password",
      hidePassword: "Hide password",
      help: "Help",
      subscriptionHelp: "This page controls the model service and core capabilities used by your subscriptions. The recommended path is Custom mode: fill in your own provider, model, base URL, and API key. Common options include OpenAI, OpenRouter, other OpenAI-compatible gateways, or your own proxy. Managed mode is available as a fallback, but stability, quotas, and availability are not guaranteed.",
      sourceSubscriptionHelp: "This page manages source subscriptions and fetch behavior. The main view only controls which sources are enabled; per-source options live inside each source's detail settings.",
      modelServiceHelp: "This page is dedicated to the model service. The desktop client currently supports only the OpenAI-compatible format, so Provider is fixed to openai. In Custom mode, fill in your own model, base URL, and API key. Common options include OpenAI, OpenRouter, other OpenAI-compatible gateways, or your own proxy. Connection testing is available only in Custom mode and is best used as a quick check before saving.",
      sourceAdvancedWarningTitle: "High-risk configuration area",
      sourceAdvancedWarningBody: "Only change these fetch parameters, account pools, or API credentials if you understand how they affect behavior. When in doubt, read the README or project docs first, then come back and adjust them carefully.",
      mailHelp: "This page is dedicated to mail hosting. The recommended path is Custom mode: enter your own SMTP server, port, sender mailbox, and password. Providers such as Gmail, Outlook, QQ Mail, and many work mail services usually expose these values in account settings. Managed mode is available as a fallback, but stability, privacy, and availability are weaker than self-hosting. Send test email is available only in Custom mode, and it will deliver a real test message to the configured receiver before saving.",
      managedMailHint: "If left empty, iDeer will try to send using a managed mailbox, but privacy and stability are weaker than self-hosting.",
      managedMailTooltip: "If you leave sender mail settings empty, iDeer may try a managed sender mailbox. This is less stable, and for privacy-sensitive use it is better to host your own mailbox service.",
      connectionHint: "Probe the current Base URL, API Key, and optional Model with an OpenAI-compatible request. It tries /models first, then falls back to a minimal chat/completions request when needed.",
      desktopPythonPath: "Python interpreter path",
      desktopPythonHint: "Desktop debug only. If set, iDeer will prefer this interpreter when starting the local service, for example the python.exe inside your conda environment.",
      testConnection: "Test connection",
      testingConnection: "Testing...",
      smtpConnectionHint: "Send a real test email to the configured receiver using the current SMTP settings.",
      testSmtp: "Send test email",
      testingSmtp: "Sending...",
      saveProfile: "Save profile",
      profileSaved: "Profile saved",
    },
    info: {
      title: "About iDeer",
      slogan: "Turn what matters each day into a clean, readable briefing.",
      disclaimerTitle: "Disclaimer",
      disclaimer: "iDeer is offered as a research-assistance and information-organization tool only, and does not provide academic, legal, financial, medical, or compliance advice. Third-party models, source feeds, mail services, and public webpages used by the app may be delayed, incomplete, inaccurate, biased, restricted, or unavailable in some regions; generated summaries, tags, recommendations, and conclusions may also be wrong. You should independently verify important content, respect copyright and platform rules, and remain responsible for your own configuration choices, email sending practices, data handling, and compliance with applicable laws and institutional policies.",
      authors: "Main Contributors",
      contributorGithubAria: (name: string) => `Open ${name}'s GitHub profile`,
      website: "Website",
      githubId: "GitHub ID",
      github: "Open GitHub repository",
      star: "Star",
      version: "Desktop prototype",
      stack: "Tauri + React + Python",
      close: "Close",
      online: "Service online",
      offline: "Service offline",
    },
    controls: {
      user: "User",
      info: "Info",
      theme: "Theme",
      language: "Language",
    },
    user: {
      fallbackName: "Your name",
      fallbackFocus: "Set your research focus",
      openProfile: "Open profile",
    },
    sourceDescriptions: {
      github: "Trending repositories and engineering momentum",
      huggingface: "Papers and model ecosystem updates",
      twitter: "Timeline signals and monitored accounts",
      arxiv: "Fresh papers and filtered research picks",
    },
    comingSoonSources: {
      wos: "Web of Science",
      cnki: "CNKI",
      wechat: "WeChat Official Accounts",
      scholar: "Google Scholar",
    },
    currentModelMissing: "Not configured",
  },
} as const;

export type AppCopy = typeof COPY.zh | typeof COPY.en;
